site:
  title: zot documentation
  start_page: zot-docs-1:developer-guide:draft-developer-guide-chapters.adoc
content:
  #Repositories to pull for docs
  sources: 
  - url: https://github.com/project-zot/docs-zot
    branches: main
output:
  clean: true
  destinations:
    - provider: archive
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll
runtime:
  fetch: true
asciidoc:
  attributes:
    toc: center
    toc-title: zot Documentation Guides
